USE Taqueria20201;
ALTER TABLE Platillo CHECK CONSTRAINT ALL;
SET IDENTITY_INSERT Platillo ON;
insert into Platillo (idPlatillo, nombre, precio) values (1, 'Taco de Pastor', 10);
insert into Platillo (idPlatillo, nombre, precio) values (2, 'Taco de Carne', 10);
insert into Platillo (idPlatillo, nombre, precio) values (3, 'Taco de Lengua', 10);
insert into Platillo (idPlatillo, nombre, precio) values (4, 'Taco de Barbacoa', 10);
insert into Platillo (idPlatillo, nombre, precio) values (5, 'Taco de Birria', 10);
insert into Platillo (idPlatillo, nombre, precio) values (6, 'Taco de Pollo', 10);
insert into Platillo (idPlatillo, nombre, precio) values (7, 'Taco de Chorizo', 10);
insert into Platillo (idPlatillo, nombre, precio) values (8, 'Taco de Atotonilco', 10);
insert into Platillo (idPlatillo, nombre, precio) values (9, 'Taco de Pescado', 10);
insert into Platillo (idPlatillo, nombre, precio) values (10, 'Taco de Longaniza', 10);
insert into Platillo (idPlatillo, nombre, precio) values (11, 'Taco de Suadero', 10);
insert into Platillo (idPlatillo, nombre, precio) values (12, 'Burrito de Carne', 40);
insert into Platillo (idPlatillo, nombre, precio) values (13, 'Burrito de Pastor', 40);
insert into Platillo (idPlatillo, nombre, precio) values (14, 'Burrito de Pollo', 40);
insert into Platillo (idPlatillo, nombre, precio) values (15, 'Quesadilla de Huitlacoche', 20);
insert into Platillo (idPlatillo, nombre, precio) values (16, 'Quesadilla de Chicharon', 20);
insert into Platillo (idPlatillo, nombre, precio) values (17, 'Quesadilla de Chorizo', 20);
insert into Platillo (idPlatillo, nombre, precio) values (18, 'Quesadilla de Tinga', 20);
insert into Platillo (idPlatillo, nombre, precio) values (19, 'Quesadilla de Frijol con Chorizo', 20);
insert into Platillo (idPlatillo, nombre, precio) values (20, 'Quesadilla de Papa', 20);
insert into Platillo (idPlatillo, nombre, precio) values (21, 'Gringa de 3', 45);
insert into Platillo (idPlatillo, nombre, precio) values (22, 'Torta de Milanesa', 35);
insert into Platillo (idPlatillo, nombre, precio) values (23, 'Torta de Pastor', 40);
insert into Platillo (idPlatillo, nombre, precio) values (24, 'Torta de Carne', 40);
insert into Platillo (idPlatillo, nombre, precio) values (25, 'Torta de Chorizo', 40);
insert into Platillo (idPlatillo, nombre, precio) values (26, 'Torta de Barbacoa', 50);
insert into Platillo (idPlatillo, nombre, precio) values (27, 'Torta de Lengua', 35);
insert into Platillo (idPlatillo, nombre, precio) values (28, 'Torta de Birria', 35);
insert into Platillo (idPlatillo, nombre, precio) values (29, 'Torta de Jamon', 30);
insert into Platillo (idPlatillo, nombre, precio) values (30, 'Torta de Pollo', 35);
insert into Platillo (idPlatillo, nombre, precio) values (31, 'Torta de Bistec', 40);
insert into Platillo (idPlatillo, nombre, precio) values (32, 'Chilaquiles', 30);
insert into Platillo (idPlatillo, nombre, precio) values (33, 'Huevos Rancheros', 40);
insert into Platillo (idPlatillo, nombre, precio) values (34, 'Huevos a la Mexicana', 40);
insert into Platillo (idPlatillo, nombre, precio) values (35, 'Huevos con Jamon', 40);
insert into Platillo (idPlatillo, nombre, precio) values (36, 'Huevos con Chorizo', 40);
insert into Platillo (idPlatillo, nombre, precio) values (37, 'Birria', 40);
insert into Platillo (idPlatillo, nombre, precio) values (38, 'Alambre', 50);
insert into Platillo (idPlatillo, nombre, precio) values (39, 'Queso Fundido', 27);
insert into Platillo (idPlatillo, nombre, precio) values (40, 'Queso Fundido con Champinones', 35);
insert into Platillo (idPlatillo, nombre, precio) values (41, 'Choriqueso', 30);
insert into Platillo (idPlatillo, nombre, precio) values (42, 'Frijoles Charros', 25);
insert into Platillo (idPlatillo, nombre, precio) values (43, 'Extra', 10);
insert into Platillo (idPlatillo, nombre, precio) values (44, 'Sincronizada', 20);
insert into Platillo (idPlatillo, nombre, precio) values (45, 'Bistec', 30);
insert into Platillo (idPlatillo, nombre, precio) values (46, 'Costilla', 30);
insert into Platillo (idPlatillo, nombre, precio) values (47, 'Coca Cola', 20);
insert into Platillo (idPlatillo, nombre, precio) values (48, 'Boing', 20);
insert into Platillo (idPlatillo, nombre, precio) values (49, 'Agua de Sabor', 15);
