USE Taqueria20201;
ALTER TABLE Salsa CHECK CONSTRAINT ALL;
SET IDENTITY_INSERT Salsa ON;
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (1, 'Salsa borracha', 'Cuarto', 'Bajo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (2, 'Salsa borracha', 'Cuarto', 'Medio', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (3, 'Salsa borracha', 'Cuarto', 'Alto', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (4, 'Salsa borracha', 'Cuarto', 'Extremo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (5, 'Salsa borracha', 'Medio', 'Bajo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (6, 'Salsa borracha', 'Medio', 'Medio', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (7, 'Salsa borracha', 'Medio', 'Alto', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (8, 'Salsa borracha', 'Medio', 'Extremo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (9, 'Salsa borracha', 'Litro', 'Bajo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (10, 'Salsa borracha', 'Litro', 'Medio', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (11, 'Salsa borracha', 'Litro', 'Alto', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (12, 'Salsa borracha', 'Litro', 'Extremo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (13, 'Salsa de molcajete', 'Cuarto', 'Bajo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (14, 'Salsa de molcajete', 'Cuarto', 'Medio', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (15, 'Salsa de molcajete', 'Cuarto', 'Alto', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (16, 'Salsa de molcajete', 'Cuarto', 'Extremo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (17, 'Salsa de molcajete', 'Medio', 'Bajo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (18, 'Salsa de molcajete', 'Medio', 'Medio', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (19, 'Salsa de molcajete', 'Medio', 'Alto', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (20, 'Salsa de molcajete', 'Medio', 'Extremo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (21, 'Salsa de molcajete', 'Litro', 'Bajo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (22, 'Salsa de molcajete', 'Litro', 'Medio', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (23, 'Salsa de molcajete', 'Litro', 'Alto', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (24, 'Salsa de molcajete', 'Litro', 'Extremo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (25, 'Salsa ranchera', 'Cuarto', 'Bajo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (26, 'Salsa ranchera', 'Cuarto', 'Medio', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (27, 'Salsa ranchera', 'Cuarto', 'Alto', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (28, 'Salsa ranchera', 'Cuarto', 'Extremo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (29, 'Salsa ranchera', 'Medio', 'Bajo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (30, 'Salsa ranchera', 'Medio', 'Medio', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (31, 'Salsa ranchera', 'Medio', 'Alto', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (32, 'Salsa ranchera', 'Medio', 'Extremo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (33, 'Salsa ranchera', 'Litro', 'Bajo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (34, 'Salsa ranchera', 'Litro', 'Medio', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (35, 'Salsa ranchera', 'Litro', 'Alto', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (36, 'Salsa ranchera', 'Litro', 'Extremo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (37, 'Salsa verde', 'Cuarto', 'Bajo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (38, 'Salsa verde', 'Cuarto', 'Medio', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (39, 'Salsa verde', 'Cuarto', 'Alto', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (40, 'Salsa verde', 'Cuarto', 'Extremo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (41, 'Salsa verde', 'Medio', 'Bajo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (42, 'Salsa verde', 'Medio', 'Medio', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (43, 'Salsa verde', 'Medio', 'Alto', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (44, 'Salsa verde', 'Medio', 'Extremo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (45, 'Salsa verde', 'Litro', 'Bajo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (46, 'Salsa verde', 'Litro', 'Medio', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (47, 'Salsa verde', 'Litro', 'Alto', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (48, 'Salsa verde', 'Litro', 'Extremo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (49, 'Salsa mexicana', 'Cuarto', 'Bajo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (50, 'Salsa mexicana', 'Cuarto', 'Medio', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (51, 'Salsa mexicana', 'Cuarto', 'Alto', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (52, 'Salsa mexicana', 'Cuarto', 'Extremo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (53, 'Salsa mexicana', 'Medio', 'Bajo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (54, 'Salsa mexicana', 'Medio', 'Medio', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (55, 'Salsa mexicana', 'Medio', 'Alto', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (56, 'Salsa mexicana', 'Medio', 'Extremo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (57, 'Salsa mexicana', 'Litro', 'Bajo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (58, 'Salsa mexicana', 'Litro', 'Medio', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (59, 'Salsa mexicana', 'Litro', 'Alto', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (60, 'Salsa mexicana', 'Litro', 'Extremo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (61, 'Salsa de chile morita', 'Cuarto', 'Bajo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (62, 'Salsa de chile morita', 'Cuarto', 'Medio', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (63, 'Salsa de chile morita', 'Cuarto', 'Alto', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (64, 'Salsa de chile morita', 'Cuarto', 'Extremo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (65, 'Salsa de chile morita', 'Medio', 'Bajo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (66, 'Salsa de chile morita', 'Medio', 'Medio', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (67, 'Salsa de chile morita', 'Medio', 'Alto', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (68, 'Salsa de chile morita', 'Medio', 'Extremo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (69, 'Salsa de chile morita', 'Litro', 'Bajo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (70, 'Salsa de chile morita', 'Litro', 'Medio', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (71, 'Salsa de chile morita', 'Litro', 'Alto', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (72, 'Salsa de chile morita', 'Litro', 'Extremo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (73, 'Salsa chipotle', 'Cuarto', 'Bajo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (74, 'Salsa chipotle', 'Cuarto', 'Medio', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (75, 'Salsa chipotle', 'Cuarto', 'Alto', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (76, 'Salsa chipotle', 'Cuarto', 'Extremo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (77, 'Salsa chipotle', 'Medio', 'Bajo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (78, 'Salsa chipotle', 'Medio', 'Medio', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (79, 'Salsa chipotle', 'Medio', 'Alto', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (80, 'Salsa chipotle', 'Medio', 'Extremo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (81, 'Salsa chipotle', 'Litro', 'Bajo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (82, 'Salsa chipotle', 'Litro', 'Medio', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (83, 'Salsa chipotle', 'Litro', 'Alto', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (84, 'Salsa chipotle', 'Litro', 'Extremo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (85, 'Salsa de jitomate', 'Cuarto', 'Bajo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (86, 'Salsa de jitomate', 'Cuarto', 'Medio', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (87, 'Salsa de jitomate', 'Cuarto', 'Alto', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (88, 'Salsa de jitomate', 'Cuarto', 'Extremo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (89, 'Salsa de jitomate', 'Medio', 'Bajo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (90, 'Salsa de jitomate', 'Medio', 'Medio', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (91, 'Salsa de jitomate', 'Medio', 'Alto', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (92, 'Salsa de jitomate', 'Medio', 'Extremo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (93, 'Salsa de jitomate', 'Litro', 'Bajo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (94, 'Salsa de jitomate', 'Litro', 'Medio', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (95, 'Salsa de jitomate', 'Litro', 'Alto', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (96, 'Salsa de jitomate', 'Litro', 'Extremo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (97, 'Salsa de cacahuate', 'Cuarto', 'Bajo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (98, 'Salsa de cacahuate', 'Cuarto', 'Medio', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (99, 'Salsa de cacahuate', 'Cuarto', 'Alto', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (100, 'Salsa de cacahuate', 'Cuarto', 'Extremo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (101, 'Salsa de cacahuate', 'Medio', 'Bajo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (102, 'Salsa de cacahuate', 'Medio', 'Medio', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (103, 'Salsa de cacahuate', 'Medio', 'Alto', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (104, 'Salsa de cacahuate', 'Medio', 'Extremo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (105, 'Salsa de cacahuate', 'Litro', 'Bajo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (106, 'Salsa de cacahuate', 'Litro', 'Medio', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (107, 'Salsa de cacahuate', 'Litro', 'Alto', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (108, 'Salsa de cacahuate', 'Litro', 'Extremo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (109, 'Salsa de chile habanero', 'Cuarto', 'Bajo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (110, 'Salsa de chile habanero', 'Cuarto', 'Medio', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (111, 'Salsa de chile habanero', 'Cuarto', 'Alto', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (112, 'Salsa de chile habanero', 'Cuarto', 'Extremo', 25);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (113, 'Salsa de chile habanero', 'Medio', 'Bajo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (114, 'Salsa de chile habanero', 'Medio', 'Medio', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (115, 'Salsa de chile habanero', 'Medio', 'Alto', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (116, 'Salsa de chile habanero', 'Medio', 'Extremo', 50);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (117, 'Salsa de chile habanero', 'Litro', 'Bajo', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (118, 'Salsa de chile habanero', 'Litro', 'Medio', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (119, 'Salsa de chile habanero', 'Litro', 'Alto', 100);
insert into Salsa (idSalsa, nombre, presentacion, nivelPicor, precio) values (120, 'Salsa de chile habanero', 'Litro', 'Extremo', 100);
