USE Taqueria20201;
ALTER TABLE Sucursal CHECK CONSTRAINT ALL;
SET IDENTITY_INSERT Sucursal ON;
SET DATEFORMAT dmy
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (1, 'Texas', 'Houston', '77266', 'Crowley', 30, '0');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (2, 'Colorado', 'Denver', '80262', 'Warbler', 14, '46');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (3, 'Georgia', 'Athens', '30605', 'Green', 39, '19');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (4, 'Tennessee', 'Nashville', '37220', 'Swallow', 4, '3');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (5, 'Arizona', 'Phoenix', '85099', 'Duke', 5, '32492');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (6, 'Texas', 'Austin', '78737', 'Nancy', 3, '753');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (7, 'California', 'Sacramento', '95818', 'Rutledge', 11, '51941');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (8, 'Arizona', 'Tempe', '85284', 'American Ash', 26, '13');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (9, 'Iowa', 'Davenport', '52809', 'Briar Crest', 8, '22786');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (10, 'Florida', 'Jacksonville', '32209', 'Hoepker', 44, '544');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (11, 'Florida', 'Saint Petersburg', '33731', 'Valley Edge', 43, '67');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (12, 'Wyoming', 'Cheyenne', '82007', 'Towne', 3, '0945');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (13, 'California', 'Alhambra', '91841', 'Forest', 41, '06');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (14, 'New York', 'Albany', '12237', 'Lakeland', 44, '7');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (15, 'Texas', 'Arlington', '76004', 'Carberry', 48, '10');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (16, 'Illinois', 'Schaumburg', '60193', 'Meadow Ridge', 35, '5');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (17, 'Minnesota', 'Saint Paul', '55127', 'Magdeline', 38, '78');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (18, 'Louisiana', 'New Orleans', '70165', 'Towne', 13, '58');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (19, 'South Carolina', 'Beaufort', '29905', 'Hansons', 7, '0356');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (20, 'New York', 'New York City', '10165', 'Fulton', 48, '9925');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (21, 'Colorado', 'Denver', '80209', 'Loeprich', 12, '6153');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (22, 'Alabama', 'Birmingham', '35279', 'Raven', 32, '00875');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (23, 'Minnesota', 'Minneapolis', '55480', 'Rigney', 22, '99');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (24, 'Texas', 'Houston', '77035', 'Farragut', 1, '53924');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (25, 'Minnesota', 'Minneapolis', '55448', 'Riverside', 43, '7091');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (26, 'California', 'Los Angeles', '90050', 'Twin Pines', 26, '75');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (27, 'Florida', 'Naples', '34114', 'Parkside', 42, '45');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (28, 'Utah', 'Salt Lake City', '84189', 'Saint Paul', 50, '34398');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (29, 'Indiana', 'Indianapolis', '46254', '1st', 43, '87');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (30, 'Florida', 'Tampa', '33686', 'Katie', 45, '652');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (31, 'Oklahoma', 'Oklahoma City', '73173', 'Cambridge', 0, '7');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (32, 'Arizona', 'Phoenix', '85062', 'Melrose', 46, '1');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (33, 'Georgia', 'Lawrenceville', '30045', 'Artisan', 37, '7591');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (34, 'Virginia', 'Virginia Beach', '23459', 'Daystar', 47, '049');
insert into Sucursal (idSucursal, estado, municipio, CP, calle, numInterno, numExterno) values (35, 'Utah', 'Salt Lake City', '84135', 'Daystar', 8, '181');
